[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[services.api]
internalPort = 5001
processes = ["app"]
protocol = "tcp"

[[services.api.ports]]
handlers = ["http"]
port = 80

[[services.api.ports]]
handlers = ["tls", "http"]
port = 443

[processes]
app = "gunicorn --bind 0.0.0.0:5001 --workers 1 --threads 1 --timeout 30 --max-requests 1000 railway_app:app"
